### ISSUE TITLE
UserController Test failures for signin and signup

### ISSUE THREAD

**Issue by Apoorva2405** [sundarsv/upgrad_course5_ass1gnment#3]
Currently, tests for signin and signup APIs are failing with 404 status:

java.lang.AssertionError: Range for response status value 404 
Expected :SUCCESSFUL
Actual   :CLIENT_ERROR
 <Click to see difference>

	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)

**Comment by Apoorva2405** [comment]
Fixed in PR:
https://github.com/sundarsv/upgrad_course5_ass1gnment/pull/29
